name: Release Documentation

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  build_html:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setupt Pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: 'latest'
          locked: true
          cache: true
          cache-write: ${{ github.ref == 'refs/heads/main' }}
          environments: doc

      - name: Build HTML
        run: |
          pixi reinstall -e doc fied
          pixi run -e doc build-doc  # This errors on warnings

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'docs/build/html'

  deploy:
    name: Deploy docs
    needs: build_html
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
